export const USERS_MAPPER = Symbol.for('ROLES_MAPPER');
export const USERS_SERVICE = Symbol.for('USERS_SERVICE');
export const USERS_REPOSITORY = Symbol.for('USERS_REPOSITORY');
export const USERS_MODEL = Symbol.for('USERS_MODEL');

export const AUTH_CREDENTIALS_SERVICE = Symbol.for('AUTH_CREDENTIALS_SERVICE');
export const AUTH_TELEGRAM_SERVICE = Symbol.for('AUTH_TELEGRAM_SERVICE');
export const AUTH_VALIDATOR_SERVICE = Symbol.for('AUTH_VALIDATOR_SERVICE');

export const TELEGRAM_USERS_MAPPER = Symbol.for('TELEGRAM_USERS_MAPPER');
export const TELEGRAM_USERS_REPOSITORY = Symbol.for('TELEGRAM_USERS_REPOSITORY');
